### ISSUE TITLE
continue up to weirdness score

### ISSUE THREAD

**Issue by durandom** [AICoE/prometheus-flatliner#12]
What are the next processors we need to build to end up with a weirdness score for a cluster?
Let's just stay in the std_dev etcd_object_count metric.

* baseline vector for ocp version
  * consumes std dev for version and adds std dev for resource if they pass a certain threshold
* vector for cluster
  * consumes std dev for cluster and adds std dev for resource to the vector
* weirdness score
  * consumes both from above and calculates score

Am I missing some?

**Comment by durandom** [comment]
@MichaelClifford could you start working on this?

**Comment by MichaelClifford** [comment]
Yes, I can start working on this. 

I'm thinking the dictionaries `clusters` in `StdDevCluster()` and  `versions` in `StdDevVersions()` already contain the info we need to represent the baseline vector and the cluster vector. So, hopefully, it just a matter of creating a third processor that calculates the L2-norm across the two. 

One issue that needs to be addressed here is the selection of the version we want to compare the cluster with. Currently we store a record for each version that passes through the app. Do we want to calculate a "weirdness" score per available version for every cluster? Or do we want to add some tooling that selects only one? Let me know how you think we should handle this?

**Comment by durandom** [comment]
> Do we want to calculate a "weirdness" score per available version for every cluster? 

Let's assume a cluster can only have one version. Then we'd calculate the score for the current version. And once a sample comes in, we just update the score.

**Comment by MichaelClifford** [comment]
Ok, so just to confirm. Say we had three clusters, 'a', 'b', and 'c' all with OCP version '1'. Then we would generate the baseline characteristic vector by looking at the resource values for all three of these clusters, updating as new data comes in. Then, determining each clusters individual score based on how much they deviate from the current version baseline, also updating as new data comes in? 

Let me know if this is that what you were thinking?

**Comment by durandom** [comment]
Yes. Isn't that exactly what we have done in the notebook too?
Michael Clifford <notifications@github.com> schrieb am Di. 30. Okt. 2018 um
20:48:

**Comment by MichaelClifford** [comment]
In the notebook we can compare any cluster to any gitVersion. I think the idea being that we would want to compare the behaviour of the current cluster with a previous stable gitVersion. However, this required manually specifying the gitVersion we wanted to compare our cluster with. But we can do it like the suggestion above for now, as I'm not sure if there is a clear mechanism for automatically selecting the previous gitVersion

**Comment by MichaelClifford** [comment]
One other question @durandom, should the other processors we build, be new flatliner classes? Or should they be additional methods within our existing flatliners?

**Comment by durandom** [comment]
like discussed via mattermost: probably a new flatliner that subscribes to std_dev_version and std_dev_cluster

**Comment by MichaelClifford** [comment]
Just submitted PR #15, that calculates the L2 distance between the current vector and the baseline of the same version.

The output values seemed rather large, and I realized I forgot to regularize the output of stddevcluster.

I will do that shortly and then I think this issue will be very nearly ready to close.

**Comment by MichaelClifford** [comment]
@durandom @subhojit-mukherjee  I think most recent PR addressees this issue.  should we close it?
