### ISSUE TITLE
refactor to use data classes

### ISSUE THREAD

**Issue by durandom** [AICoE/prometheus-flatliner#24]
instead of passing around dicts, we should create a data class for each structure to be passed around.

https://github.com/ericvsmith/dataclasses
this implements data classes for python3.6 
in 3.7 they'll be available by default
it's much nicer than dicts
https://docs.python.org/3/library/dataclasses.html
and you might want to rebase your fork for the stuff I've merged upstream

**Comment by MichaelClifford** [comment]
Work in PR #37 implements data classes for all processors except for `clusteralertcorr` and `gitversionalertcorr`. Those will be addressed in a future PR.

**Comment by MichaelClifford** [comment]
I think current work is sufficient to close this issue. Moving forward we are using data classes for all processors.
