### ISSUE TITLE
Calculation Validation

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/prometheus-flatliner#8]
We need to create methods for validating that our on-line standard deviation and correlation calculations are correct and equal to the same result if we had access to all data at once. 

These will not be used in the final version, but necessary to confirm our approach.   

Initial idea, would just be to collect all the values in a list as we iterate through the data, and then perform stdev() or corr() on the final output to confirm that our results match.

**Comment by MichaelClifford** [comment]
I have validated that `calculate_stdv()` produces the same result as if we had access to all data.

**Comment by durandom** [comment]
That should be part of the unit tests.
@fridex what unit test framewok would you recommend? We should use the same as you are using for thoth

**Comment by fridex** [comment]
> @fridex what unit test framewok would you recommend? We should use the same as you are using for thoth

Here are some frameworks we use and are popular in python:

* [pytest](https://docs.pytest.org/) - it has a very nice user base and is extensible, a lot of plugins can be found
* [hypothesis](https://hypothesis.readthedocs.io/en/latest/) - can be especially useful for data scientists
* [flexmock](https://flexmock.readthedocs.io/en/latest/) - useful for mocking
