### ISSUE TITLE
possibility to filter on OCP version 

### ISSUE THREAD

**Issue by durandom** [AICoE/prometheus-flatliner#83]
for the deployment in app-sre we're only interested in some versions of OCP4. For that we need to be able to filter on specific versions. E.g. the CI versions are like `0.0...` but the version we're interested in are like `4.0.0-0.1`. See the [documentation on metrics](https://docs.google.com/document/d/12FJmLFQ6qf8slmOleWgIousaMUrhWGHR3vwfDeABKO8/edit#)

Let's introduce 
* a filter flatliner, that is similar to https://github.com/AICoE/prometheus-flatliner/blob/master/flatliners/versionedmetrics.py
* this is hooked between versioned_metrics and single_metrics [here](https://github.com/AICoE/prometheus-flatliner/blob/master/app.py#L56)
* it drops all metrics that don't match a regular expression that can be configured via an ENV variable.

**Comment by 4n4nd** [comment]
Maybe this regex string (`"^[0-9]*\.[0-9]*\.[0-9]*-[0-9]*\.[0-9]*$"`) would filter all the CI versions, alpha versions and `None`s

**Comment by 4n4nd** [comment]
Should be implemented in the following PR: https://github.com/AICoE/prometheus-flatliner/pull/85
