### ISSUE TITLE
clear stale clusters etc from caches / lookups

### ISSUE THREAD

**Issue by durandom** [AICoE/prometheus-flatliner#84]
please look into every flatliner and identify possible memory bloats.
e.g. [here](https://github.com/AICoE/prometheus-flatliner/blob/master/flatliners/versionedmetrics.py#L40) we build up `cluster_versions` with all cluster_ids and never remove old entries.

Maybe you can use some better object than a dict for this purpose. E.g https://cachetools.readthedocs.io/en/stable/#

**Comment by durandom** [comment]
or https://github.com/mailgun/expiringdict

**Comment by 4n4nd** [comment]
I like the LRU Cache implementation in cachetools better (https://cachetools.readthedocs.io/en/stable/#cachetools.LRUCache)
