### ISSUE TITLE
Recording Rules in thanos or Prometheus hosts to improve query time

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-flatliner#88]
Maybe we could add a recording rule to Thanos that pre-computes our query, improving the query time. (https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules)

**Comment by durandom** [comment]
what query do you mean?

**Comment by 4n4nd** [comment]
the metric lookup query for flatliners, we know we are going to request for 5mins of data for cluster_version metric, every 5 mins

**Comment by durandom** [comment]
I still don't understand. can you show me the rule you'd like to add?

**Comment by 4n4nd** [comment]
Example rule could be something like this,
```
- record: etcd_object_count_past_5m
  expr: etcd_object_count[5m]
```
Would this work then?

**Comment by durandom** [comment]
I dont think that makes sense... 
recording rules are for calculations, like `count(etc_object_count)`

I dont even think such a rule, with a time vector is even possible

**Comment by 4n4nd** [comment]
https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules

Wouldn't this count as a frequently needed expression?

**Comment by 4n4nd** [comment]
I saw some rules like it here: https://github.com/infinityworks/prometheus-example-queries

**Comment by durandom** [comment]
these are all calculations. we just download all metrics...
